In [69]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

df_orig = pd.read_csv('../data/raw/EDC_OXFORDSHIRE_2015_2025.csv', usecols= [
    'certificate_number', 'address1', 'address2', 'address3', 'postcode',
    'posttown', 'address', 'local_authority', 'local_authority_label',
    'built_form', 'construction_age_band', 'current_energy_efficiency',
    'current_energy_rating', 'energy_consumption_current', 'extension_count', 'floor_height', 'heating_cost_current',
    'inspection_date', 'lodgement_date', 'number_habitable_rooms',
    'number_heated_rooms', 'potential_energy_efficiency', 'property_type',
    'tenure', 'total_floor_area', 'transaction_type', 'uprn', 'uprn_source'])

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.expand_frame_repr', False)

In [70]:
df_new = pd.read_csv('../data/raw/EDC_OXFORDSHIRE_2008_2025.csv', usecols= [
    'certificate_number', 'address1', 'address2', 'address3', 'postcode',
    'posttown', 'address', 'local_authority', 'local_authority_label',
    'built_form', 'construction_age_band', 'current_energy_efficiency',
    'current_energy_rating', 'energy_consumption_current', 'extension_count', 'floor_height', 'heating_cost_current',
    'inspection_date', 'lodgement_date', 'number_habitable_rooms',
    'number_heated_rooms', 'potential_energy_efficiency', 'property_type',
    'tenure', 'total_floor_area', 'transaction_type', 'uprn', 'uprn_source'])

In [71]:
(df_orig.columns == df_new.columns).mean()

np.float64(1.0)

All columns match

In [72]:
df_orig.info()

<class 'pandas.DataFrame'>
RangeIndex: 216054 entries, 0 to 216053
Data columns (total 28 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   certificate_number           216054 non-null  str
 1   address1                     216054 non-null  str
 2   address2                     117532 non-null  str
 3   address3                     27304 non-null   str
 4   postcode                     216054 non-null  str
 5   posttown                     213327 non-null  str
 6   address                      216054 non-null  str
 7   local_authority              216054 non-null  str
 8   local_authority_label        216054 non-null  str
 9   built_form                   213548 non-null  str
 10  construction_age_band        216054 non-null  str
 11  current_energy_efficiency    216054 non-null  int64
 12  current_energy_rating        216054 non-null  str
 13  energy_consumption_current   216054 non-null  int64
 14  extension_count              166635 non-null  float64
 15  floor_height                 214439 non-null  float64
 16  heating_cost_current         216054 non-null  int64
 17  inspection_date              216054 non-null  str
 18  lodgement_date               216054 non-null  str
 19  number_habitable_rooms       166635 non-null  float64
 20  number_heated_rooms          166635 non-null  float64
 21  potential_energy_efficiency  216054 non-null  int64
 22  property_type                216047 non-null  str
 23  tenure                       216054 non-null  str
 24  total_floor_area             216054 non-null  int64
 25  transaction_type             215580 non-null  str
 26  uprn                         214736 non-null  float64
 27  uprn_source                  214736 non-null  str
dtypes: float64(5), int64(5), str(18)
memory usage: 89.0 MB

In [73]:
df_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 338323 entries, 0 to 338322
Data columns (total 28 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   certificate_number           338323 non-null  str
 1   address1                     338323 non-null  str
 2   address2                     177517 non-null  str
 3   address3                     40926 non-null   str
 4   postcode                     338323 non-null  str
 5   posttown                     335596 non-null  str
 6   address                      338323 non-null  str
 7   local_authority              338323 non-null  str
 8   local_authority_label        338323 non-null  str
 9   built_form                   331753 non-null  str
 10  construction_age_band        338309 non-null  str
 11  current_energy_efficiency    338323 non-null  int64
 12  current_energy_rating        338323 non-null  str
 13  energy_consumption_current   338323 non-null  float64
 14  extension_count              276956 non-null  float64
 15  floor_height                 336146 non-null  float64
 16  heating_cost_current         338323 non-null  float64
 17  inspection_date              338323 non-null  str
 18  lodgement_date               338323 non-null  str
 19  number_habitable_rooms       276956 non-null  float64
 20  number_heated_rooms          276956 non-null  float64
 21  potential_energy_efficiency  338323 non-null  int64
 22  property_type                338316 non-null  str
 23  tenure                       252946 non-null  str
 24  total_floor_area             337984 non-null  float64
 25  transaction_type             337814 non-null  str
 26  uprn                         335700 non-null  float64
 27  uprn_source                  335700 non-null  str
dtypes: float64(8), int64(2), str(18)
memory usage: 138.8 MB

In [74]:
print(df_new.isna().sum())

certificate_number                  0
address1                            0
address2                       160806
address3                       297397
postcode                            0
posttown                         2727
address                             0
local_authority                     0
local_authority_label               0
built_form                       6570
construction_age_band              14
current_energy_efficiency           0
current_energy_rating               0
energy_consumption_current          0
extension_count                 61367
floor_height                     2177
heating_cost_current                0
inspection_date                     0
lodgement_date                      0
number_habitable_rooms          61367
number_heated_rooms             61367
potential_energy_efficiency         0
property_type                       7
tenure                          85377
total_floor_area                  339
transaction_type                  509
uprn                             2623
uprn_source                      2623
dtype: int64

In [75]:
print(df_orig.isna().sum())

certificate_number                  0
address1                            0
address2                        98522
address3                       188750
postcode                            0
posttown                         2727
address                             0
local_authority                     0
local_authority_label               0
built_form                       2506
construction_age_band               0
current_energy_efficiency           0
current_energy_rating               0
energy_consumption_current          0
extension_count                 49419
floor_height                     1615
heating_cost_current                0
inspection_date                     0
lodgement_date                      0
number_habitable_rooms          49419
number_heated_rooms             49419
potential_energy_efficiency         0
property_type                       7
tenure                              0
total_floor_area                    0
transaction_type                  474
uprn                             1318
uprn_source                      1318
dtype: int64

- tenure has a large number of missing values in the new set. These rows will be kept. Current cleaning only converts 'unknown' to null, should still work.
- Rows with nulls in total_floor_area may need to be excluded if they make it through to the end

In [84]:
print('Decimals:')
for c in ['total_floor_area', 'heating_cost_current', 'energy_consumption_current']:
    print(f"{c}: {(df_new[c].dropna() % 1 != 0).sum()}")

Decimals:
total_floor_area: 0
heating_cost_current: 5
energy_consumption_current: 4

In [77]:
mask = df_new['heating_cost_current'] % 1 != 0
df_new[mask]

              certificate_number               address1        address2   address3  postcode   posttown                                   address local_authority local_authority_label            built_form           construction_age_band  current_energy_efficiency current_energy_rating  energy_consumption_current  extension_count  floor_height  heating_cost_current inspection_date lodgement_date  number_habitable_rooms  number_heated_rooms  potential_energy_efficiency property_type tenure  total_floor_area transaction_type          uprn      uprn_source
56604   8948-6138-5400-3195-2006  Flat 2 Cherwell Court  Britannia Road        NaN  OX16 5DE    BANBURY     Flat 2 Cherwell Court, Britannia Road       E07000177              Cherwell                   NaN                             NaN                         77                     C                     179.450              NaN           NaN               247.240      2008-08-05     2008-09-24                     NaN                  NaN                           78          Flat    NaN               NaN     new dwelling  1.001191e+10  Energy Assessor
126973  8578-6820-5049-0193-4002          Black Poplars  Standlake Road  Northmoor  OX29 5AY     WITNEY  Black Poplars, Standlake Road, Northmoor       E07000181      West Oxfordshire              Detached  England and Wales: before 1900                         83                     B                      98.690              NaN           0.0               192.190      2008-10-07     2008-10-07                     NaN                  NaN                           85         House    NaN               0.0     new dwelling  1.003323e+10  Energy Assessor
234267  2468-9088-6206-6541-0064            Pusey House           Pusey        NaN   SN7 8QB  FARINGDON                        Pusey House, Pusey       E07000180   Vale of White Horse              Detached  England and Wales: before 1900                         35                     F                     266.000              0.0           2.3                 1.804      2009-06-26     2009-06-30                    25.0                 25.0                           48         House    NaN            2191.0    marketed sale  1.001403e+10  Energy Assessor
266452  8141-6222-5980-1821-3092       9 Ridgeway Court    Wolage Drive      Grove  OX12 9NP    WANTAGE     9 Ridgeway Court, Wolage Drive, Grove       E07000180   Vale of White Horse  Enclosed End-Terrace                       2003-2006                          1                     G                       1.161              0.0         204.0                 2.210      2009-02-19     2009-02-23                     4.0                  4.0                            1          Flat    NaN              85.0    marketed sale  1.001408e+10  Energy Assessor
338073  9750-2813-6004-0808-7435          Black Poplars  Standlake Road  Northmoor  OX29 5AY     WITNEY  Black Poplars, Standlake Road, Northmoor       E07000181      West Oxfordshire              Detached  England and Wales: before 1900                         81                     B                      86.850              NaN           0.0               163.710      2008-10-07     2008-10-14                     NaN                  NaN                           83         House    NaN               0.0     new dwelling  1.003323e+10  Energy Assessor

In [85]:
mask = df_new['energy_consumption_current'] % 1 != 0
df_new[mask]

              certificate_number               address1        address2   address3  postcode posttown                                   address local_authority local_authority_label            built_form           construction_age_band  current_energy_efficiency current_energy_rating  energy_consumption_current  extension_count  floor_height  heating_cost_current inspection_date lodgement_date  number_habitable_rooms  number_heated_rooms  potential_energy_efficiency property_type tenure  total_floor_area transaction_type          uprn      uprn_source  dayofweek  day  month  quarter  year
56604   8948-6138-5400-3195-2006  Flat 2 Cherwell Court  Britannia Road        NaN  OX16 5DE  BANBURY     Flat 2 Cherwell Court, Britannia Road       E07000177              Cherwell                   NaN                             NaN                         77                     C                     179.450              NaN           NaN                247.24      2008-08-05     2008-09-24                     NaN                  NaN                           78          Flat    NaN               NaN     new dwelling  1.001191e+10  Energy Assessor          2   24      9        3  2008
126973  8578-6820-5049-0193-4002          Black Poplars  Standlake Road  Northmoor  OX29 5AY   WITNEY  Black Poplars, Standlake Road, Northmoor       E07000181      West Oxfordshire              Detached  England and Wales: before 1900                         83                     B                      98.690              NaN           0.0                192.19      2008-10-07     2008-10-07                     NaN                  NaN                           85         House    NaN               0.0     new dwelling  1.003323e+10  Energy Assessor          1    7     10        4  2008
266452  8141-6222-5980-1821-3092       9 Ridgeway Court    Wolage Drive      Grove  OX12 9NP  WANTAGE     9 Ridgeway Court, Wolage Drive, Grove       E07000180   Vale of White Horse  Enclosed End-Terrace                       2003-2006                          1                     G                       1.161              0.0         204.0                  2.21      2009-02-19     2009-02-23                     4.0                  4.0                            1          Flat    NaN              85.0    marketed sale  1.001408e+10  Energy Assessor          0   23      2        1  2009
338073  9750-2813-6004-0808-7435          Black Poplars  Standlake Road  Northmoor  OX29 5AY   WITNEY  Black Poplars, Standlake Road, Northmoor       E07000181      West Oxfordshire              Detached  England and Wales: before 1900                         81                     B                      86.850              NaN           0.0                163.71      2008-10-07     2008-10-14                     NaN                  NaN                           83         House    NaN               0.0     new dwelling  1.003323e+10  Energy Assessor          1   14     10        4  2008

- 2015-2025- float64(5), int64(5), str(18)
- 2008-2025 - float64(8), int64(2), str(18)
- 3 Int have become floats
    - total_floor_area
        - contains 339 nulls in 2008-2025 dataset (0.1%) none in 2015-2025
        - no decimals in remaining
    - heating_cost_current
        - no nulls
        - 5 decimals in remaining (247.240, 192.190, 1.804, 2.210, 163.710), 3 have NaN number_habitable_rooms and null or 0 total_floor area, 1 of the others (2.210) is a flat with 4 rooms and G current_energy_rating (suspect), and the last (1.804) has 25 rooms (such low heating cost makes no sense)
    - energy_consumption_current
        - no nulls
        - 4 decimals, 3 are in rows with null rooms (will be filtered out). Remaining row was also flagged in heating_cost_current and is a Flat with 204m floor_height (impossible)

In [78]:
for n in [df_orig, df_new]:
    n['inspection_date'] = n['inspection_date'].astype('datetime64[ns]')
    n['lodgement_date'] = n['lodgement_date'].astype('datetime64[ns]')
    n['dayofweek'] = n['lodgement_date'].dt.dayofweek
    n['day'] = n['lodgement_date'].dt.day
    n['month'] = n['lodgement_date'].dt.month
    n['quarter'] = n['lodgement_date'].dt.quarter
    n['year'] = n['lodgement_date'].dt.year

In [79]:
print(df_new.groupby('year')['certificate_number'].count())
print(df_new['lodgement_date'].value_counts().sort_index())

year
2008     8399
2009    24182
2010    18664
2011    16329
2012    18230
2013    17909
2014    18558
2015    18392
2016    15318
2017    15269
2018    19921
2019    21695
2020    20219
2021    22562
2022    22252
2023    20424
2024    19974
2025    20026
Name: certificate_number, dtype: int64
lodgement_date
2008-09-22     78
2008-09-23     85
2008-09-24     95
2008-09-25    102
2008-09-26     80
             ...
2025-12-27      4
2025-12-28      2
2025-12-29     10
2025-12-30     14
2025-12-31      8
Name: count, Length: 6247, dtype: int64

- New file has lodgements in every expected year, running from Sept 2008 to end of 2025. 2009 has most lodgements, which is plausible as new Home-Information-Packs for every sale were still in place until 2010.

In [80]:
print(df_orig['lodgement_date'].value_counts().sort_index())
print(df_orig.shape[0])

lodgement_date
2015-01-02    19
2015-01-03     1
2015-01-04     3
2015-01-05    41
2015-01-06    51
              ..
2025-12-27     4
2025-12-28     2
2025-12-29    10
2025-12-30    14
2025-12-31     8
Name: count, Length: 3981, dtype: int64
216054

In [81]:
print(df_new[(df_new['lodgement_date'] >= '2015-01-01') & (df_new['lodgement_date'] <= '2025-12-31')].shape[0])
print(df_new[(df_new['lodgement_date'] >= '2015-01-01') & (df_new['lodgement_date'] <= '2025-12-31')]['lodgement_date'].value_counts().sort_index())

216052
lodgement_date
2015-01-02    19
2015-01-03     1
2015-01-04     3
2015-01-05    41
2015-01-06    51
              ..
2025-12-27     4
2025-12-28     2
2025-12-29    10
2025-12-30    14
2025-12-31     8
Name: count, Length: 3981, dtype: int64

- New dataset contains 2 less rows in the 2015-2025 window

In [82]:
print(f"2008-2025: {df_new[(df_new['lodgement_date'] >= '2015-01-01') & (df_new['lodgement_date'] <= '2025-12-31')].nunique()['certificate_number']}")
print(f"2015-2025: {df_orig['certificate_number'].nunique()}")

2008-2025: 216052
2015-2025: 216054

- New dataset contains 2 less unique values in certificate_number

In [83]:
print(df_orig['local_authority'].value_counts())
print(df_new['local_authority'].value_counts())

local_authority
E07000177    47544
E07000178    45721
E07000180    45639
E07000179    42271
E07000181    34875
E07000221        4
Name: count, dtype: int64
local_authority
E07000178    75916
E07000177    73585
E07000180    67325
E07000179    66571
E07000181    54921
E07000221        4
E06000060        1
Name: count, dtype: int64

- Both sets contain the 5 expected local authorities. The new set has an extra spurious row with E06000060 local authority.